# Generated by Django 3.0.5 on 2020-04-13 07:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mp', models.CharField(blank=True, max_length=11)),
                ('id_number', models.CharField(blank=True, max_length=18)),
                ('wechat', models.CharField(blank=True, max_length=11)),
                ('score_id', models.CharField(max_length=21, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_staffuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('payment_type', models.CharField(choices=[('CASH', 'cash'), ('scores', 'scores')], default='cash', max_length=12)),
                ('orderscoreid', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField(default=0)),
                ('orderdate', models.DateField(null=True)),
                ('orderer_sc', models.IntegerField(default=0, null=True)),
                ('up1_sc', models.IntegerField(default=0, null=True)),
                ('up2_sc', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=12)),
                ('description_status', models.CharField(default='', max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('catalog', models.CharField(blank=True, max_length=18)),
                ('unit', models.CharField(blank=True, max_length=12)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('place', models.CharField(blank=True, max_length=18)),
                ('details', models.TextField(blank=True)),
                ('is_onsale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_daily_used', models.BooleanField(default=True)),
                ('receiver_name', models.CharField(max_length=20)),
                ('receiver_mp', models.CharField(blank=True, max_length=11)),
                ('receiver_province', models.CharField(max_length=20)),
                ('receiver_city', models.CharField(max_length=20)),
                ('receiver_dist', models.CharField(max_length=20)),
                ('receiver_addr', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fmarket.EndUser')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(blank=True)),
                ('ship_cmpn', models.CharField(max_length=16)),
                ('ship_num', models.CharField(max_length=16)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accept_date', models.DateField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fmarket.ShippingAddress')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fmarket.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='OrderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fmarket.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='Fmarket.Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_orderscore', to='Fmarket.EndUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Fmarket.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='up1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up1', to='Fmarket.EndUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='up2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up2', to='Fmarket.EndUser'),
        ),
    ]
