# Generated by Django 3.0.5 on 2020-04-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Fmarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='up1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='up2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
