# Generated by Django 3.0.3 on 2020-04-25 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0002_auto_20200421_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 25, 19, 52, 59, 22880)),
        ),
    ]
