# Generated by Django 3.0.5 on 2020-04-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('catalog', models.CharField(blank=True, max_length=18)),
                ('unit', models.CharField(blank=True, max_length=12)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('place', models.CharField(blank=True, max_length=18)),
                ('details', models.TextField(blank=True)),
                ('is_onsale', models.BooleanField(default=True)),
            ],
        ),
    ]
