# Generated by Django 3.0.5 on 2020-08-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_userimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('adddate', models.DateField(auto_now=True, verbose_name='加入购物车日期')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_product', to='User.EndUser', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cart', to='User.EndUser', verbose_name='顾客')),
            ],
        ),
    ]
