# Generated by Django 3.0.5 on 2020-08-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='购物车ID'),
        ),
    ]
