# Generated by Django 3.0.5 on 2020-08-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productimgs'),
        ('Cart', '0002_auto_20200817_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_product', to='Product.Products', verbose_name='商品'),
        ),
    ]
