# Generated by Django 3.0.5 on 2020-04-14 01:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mp', models.CharField(blank=True, max_length=11)),
                ('id_number', models.CharField(blank=True, max_length=18)),
                ('wechat', models.CharField(blank=True, max_length=11)),
                ('score_id', models.CharField(max_length=21, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_staffuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
