# Generated by Django 3.0.5 on 2020-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='是卖家'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='is_staffuser',
            field=models.BooleanField(default=False, verbose_name='是管理者'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='mp',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='score_id',
            field=models.CharField(max_length=21, unique=True, verbose_name='积分ID'),
        ),
    ]
