# Generated by Django 3.0.3 on 2020-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200416_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='wechat',
            field=models.CharField(blank=True, max_length=11, verbose_name='微信'),
        ),
    ]
