# Generated by Django 3.0.5 on 2020-08-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200425_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(blank=True, max_length=18)),
                ('image', models.ImageField(height_field=160, max_length=300, upload_to='media', width_field=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.EndUser')),
            ],
        ),
    ]
