# Generated by Django 3.0.5 on 2020-04-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('User', '0001_initial'),
        ('Pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_orderscore', to='User.EndUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Pay.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='up1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up1', to='User.EndUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='up2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up2', to='User.EndUser'),
        ),
    ]
