# Generated by Django 3.0.5 on 2020-04-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200416_1237'),
        ('Product', '0001_initial'),
        ('Order', '0002_auto_20200414_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderStatus',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.OrderStatus', verbose_name='订单状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='Product.Products', verbose_name='订单商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(null=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_orderscore', to='User.EndUser', verbose_name='下单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer_sc',
            field=models.IntegerField(default=0, null=True, verbose_name='订单积分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderscoreid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单自然ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='up1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up1', to='User.EndUser', verbose_name='上一级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='up1_sc',
            field=models.IntegerField(default=0, null=True, verbose_name='上一级积分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='up2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_up2', to='User.EndUser', verbose_name='上二级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='up2_sc',
            field=models.IntegerField(default=0, null=True, verbose_name='上二级积分'),
        ),
    ]
