# Generated by Django 3.0.5 on 2020-04-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0001_initial'),
        ('Order', '0003_auto_20200416_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pay.Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'cash'), ('SCORES', 'scores')], default='cash', max_length=12),
        ),
    ]
