# Generated by Django 3.0.5 on 2020-08-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userimg'),
        ('Order', '0004_auto_20200416_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_orderscore', to='User.EndUser', verbose_name='顾客'),
        ),
    ]
